# Generated by Django 6.0.4 on 2026-04-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='code_fournisseur',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='date_premiere_contact',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
