# Generated by Django 6.0.4 on 2026-04-21 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('echantillons', '0002_remove_echantillon_reference_bouteille'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationOrganoleptique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('soumis', 'Soumis')], default='en_cours', max_length=20)),
                ('fruite', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('amertume', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('piquant', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('chomage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('moisi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('vinaigre', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('rance', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('degustateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('echantillon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='echantillons.echantillon')),
            ],
            options={
                'unique_together': {('echantillon', 'degustateur')},
            },
        ),
    ]
