# Generated by Django 6.0.4 on 2026-04-22 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
        ('sessions_degustation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationorganoleptique',
            name='autres_defaut',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationorganoleptique',
            name='classification',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='evaluationorganoleptique',
            name='fruite_vert',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='evaluationorganoleptique',
            name='gele',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='evaluationorganoleptique',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='sessions_degustation.sessiondegustation'),
        ),
    ]
