# Generated by Django 6.0.4 on 2026-04-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_evaluationorganoleptique_autres_defaut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationorganoleptique',
            old_name='chomage',
            new_name='chome',
        ),
        migrations.RenameField(
            model_name='evaluationorganoleptique',
            old_name='date_evaluation',
            new_name='soumis_le',
        ),
        migrations.AddField(
            model_name='evaluationorganoleptique',
            name='autres_defaut_nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='evaluationorganoleptique',
            name='autres_defaut',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
