# Generated by Django 6.0.4 on 2026-05-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_rename_chomage_evaluationorganoleptique_chome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationorganoleptique',
            name='soumis_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
