# Generated by Django 6.0.4 on 2026-04-21 23:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('echantillons', '0002_remove_echantillon_reference_bouteille'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificationLivraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('date_exacte', 'Date exacte'), ('periode', 'Période')], default='date_exacte', max_length=20)),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('heure', models.TimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('numero_camion', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('echantillon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planification_livraison', to='echantillons.echantillon')),
            ],
        ),
    ]
