# Generated by Django 6.0.4 on 2026-04-22 02:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echantillons', '0004_rename_reference_echantillon_ref_and_more'),
        ('planifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planificationlivraison',
            old_name='date_livraison',
            new_name='date_exacte',
        ),
        migrations.RenameField(
            model_name='planificationlivraison',
            old_name='date_debut',
            new_name='periode_debut',
        ),
        migrations.RenameField(
            model_name='planificationlivraison',
            old_name='date_fin',
            new_name='periode_fin',
        ),
        migrations.RemoveField(
            model_name='planificationlivraison',
            name='numero_camion',
        ),
        migrations.AddField(
            model_name='planificationlivraison',
            name='camion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='PlanificationArrivage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('date_exacte', 'Date exacte'), ('periode', 'Période')], default='date_exacte', max_length=20)),
                ('date_exacte', models.DateField(blank=True, null=True)),
                ('periode_debut', models.DateField(blank=True, null=True)),
                ('periode_fin', models.DateField(blank=True, null=True)),
                ('echantillon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planification_arrivage', to='echantillons.echantillon')),
            ],
        ),
    ]
