# Generated by Django 6.0.4 on 2026-04-21 23:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('echantillons', '0002_remove_echantillon_reference_bouteille'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('NOUVEL_ECHANTILLON', 'Nouvel échantillon'), ('ECHANTILLON_MODIFIE', 'Échantillon modifié'), ('ECHANTILLON_SUPPRIME', 'Échantillon supprimé'), ('ECHANTILLON_RECU', 'Échantillon reçu physiquement'), ('PREMIERE_EVALUATION', 'Première évaluation soumise'), ('TOUTES_EVALUATIONS', 'Toutes les évaluations soumises'), ('ANALYSE_SOUMISE', 'Analyse laboratoire soumise'), ('ACHAT_CONFIRME', 'Achat confirmé')], max_length=40)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('section', models.CharField(choices=[('ECHANTILLONS', 'Échantillons'), ('EVALUATIONS', 'Évaluations'), ('ANALYSES', 'Analyses'), ('ACHATS', 'Achats')], default='ECHANTILLONS', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('echantillon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='echantillons.echantillon')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
