# Generated by Django 6.0.4 on 2026-09-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NOUVEL_ECHANTILLON', 'Nouvel echantillon'), ('ECHANTILLON_MODIFIE', 'Echantillon modifie'), ('ECHANTILLON_SUPPRIME', 'Echantillon supprime'), ('ECHANTILLON_RECU', 'Echantillon recu physiquement'), ('RECEPTION_ANNULEE', 'Reception physique annulee'), ('PREMIERE_EVALUATION', 'Premiere evaluation soumise'), ('EVALUATION_SOUMISE', 'Evaluation soumise'), ('TOUTES_EVALUATIONS', 'Toutes les evaluations soumises'), ('ANALYSE_SOUMISE', 'Analyse laboratoire soumise'), ('ACHAT_CONFIRME', 'Achat confirme'), ('proposition_achat_attente', "Proposition d'achat en attente"), ('ANALYSE_URGENTE', 'Analyse urgente demandee'), ('EVALUATION_URGENTE', 'Evaluation urgente demandee'), ('DATE_LIVRAISON_AJOUTEE', 'Date de livraison ajoutee'), ('DATE_LIVRAISON_MODIFIEE', 'Date de livraison modifiee'), ('NOUVELLE_SESSION', 'Nouvelle session'), ('NEGOCIATION_PROPOSEE', 'Negociation proposee'), ('NEGOCIATION_MISE_A_JOUR', 'Negociation mise a jour'), ('NEGOCIATION_A_REVOIR', 'Negociation a revoir')], max_length=40),
        ),
    ]
