# Generated by Django 6.0.4 on 2026-04-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='lu_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
