# Generated by Django 6.0.4 on 2026-09-11 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echantillons', '0013_echantillon_date_reception_echantillon'),
        ('messages_chat', '0002_message_lu_le'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='echantillon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='echantillons.echantillon'),
        ),
        migrations.AddField(
            model_name='message',
            name='modifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='modifie_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
