# Generated by Django 6.0.4 on 2026-04-21 22:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('echantillons', '0002_remove_echantillon_reference_bouteille'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDegustation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('lieu', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='planifiee', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_creees', to=settings.AUTH_USER_MODEL)),
                ('echantillons', models.ManyToManyField(blank=True, related_name='sessions', to='echantillons.echantillon')),
                ('participants', models.ManyToManyField(blank=True, related_name='sessions_invitees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
