# Generated by Django 6.0.4 on 2026-04-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_degustation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondegustation',
            name='statut',
            field=models.CharField(choices=[('en_attente_validation', 'En attente de validation'), ('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='en_attente_validation', max_length=25),
        ),
    ]
