# Generated by Codex on 2026-05-11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions_degustation', '0003_alter_sessiondegustation_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondegustation',
            name='nombre_echantillons_prevus',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessiondegustation',
            name='presences_confirmees',
            field=models.ManyToManyField(
                blank=True,
                related_name='sessions_presence_confirmee',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
