# Generated by Django 6.0.4 on 2026-10-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_degustation', '0004_session_presence_and_expected_samples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondegustation',
            name='heure',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessiondegustation',
            name='lieu',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
