# Generated by Django 6.0.4 on 2026-04-21 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('echantillons', '0002_remove_echantillon_reference_bouteille'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseLabo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('soumis', 'Soumis')], default='en_cours', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='analyses/')),
                ('notes', models.TextField(blank=True)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('echantillon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse', to='echantillons.echantillon')),
                ('technicien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CritereAnalyse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('valeur', models.CharField(max_length=100)),
                ('unite', models.CharField(blank=True, max_length=50)),
                ('valeur_min', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('valeur_max', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to='analyses.analyselabo')),
            ],
        ),
    ]
