# Generated by Django 6.0.4 on 2026-04-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='critereanalyse',
            name='conforme',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
