# Generated by Django 6.0.4 on 2026-04-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_critereanalyse_conforme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critereanalyse',
            name='unite',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='critereanalyse',
            name='valeur',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='critereanalyse',
            name='valeur_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='critereanalyse',
            name='valeur_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
