# Generated by Django 6.0.4 on 2026-05-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_alter_critereanalyse_unite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyselabo',
            name='acidite',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='delta_k',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='humidite',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='impuretes',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='indice_peroxyde',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='k232',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='k270',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
