# Generated by Django 6.0.4 on 2026-08-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0004_analyselabo_acidite_analyselabo_delta_k_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyselabo',
            name='acide_arachidique',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='acide_gadoleique',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='acide_heptadecanoique',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='acide_heptadecenoique',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='acide_linoleique',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='acide_linolenique',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='acide_oleique',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='acide_palmitique',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='acide_palmitoleique',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='acide_stearique',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='beta_sitosterol_apparent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='brassicasterol',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='campesterol',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='cholesterol',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='date_debut_analyse',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='date_fin_analyse',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='delta_7_avenasterol',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='delta_7_stigmastenol',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='ecn42',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='erythrodiol_uvaol',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='numero_certificat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='numero_lot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='quantite_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='stigmasterol',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='trans_c18_1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='analyselabo',
            name='trans_c18_2_c18_3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
