# Generated by Django 6.0.4 on 2026-04-21 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Echantillon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('gouvernorat', models.CharField(max_length=100)),
                ('delegation', models.CharField(blank=True, max_length=100)),
                ('reference_bouteille', models.CharField(max_length=100)),
                ('variete', models.CharField(blank=True, max_length=100)),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nombre_bouteilles', models.IntegerField(blank=True, null=True)),
                ('statut_collecteur', models.CharField(choices=[('receptionne', 'Réceptionné'), ('en_negociation', 'En négociation'), ('achat_confirme', 'Achat confirmé')], default='receptionne', max_length=20)),
                ('statut_degustateur', models.CharField(choices=[('non_evaluee', 'Non évaluée'), ('en_cours', 'Évaluation en cours'), ('soumis', 'Évaluation soumise')], default='non_evaluee', max_length=20)),
                ('statut_labo', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('soumis', 'Soumis')], default='en_attente', max_length=20)),
                ('recu_physiquement', models.BooleanField(default=False)),
                ('date_reception_echantillon', models.DateField(blank=True, null=True)),
                ('budget_negociation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_livraison_stock_souhaitee', models.DateField(blank=True, null=True)),
                ('prix_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('camion_livraison', models.CharField(blank=True, max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('collecteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echantillons_collectes', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echantillons', to='fournisseurs.fournisseur')),
            ],
        ),
    ]
