# Generated by Django 6.0.4 on 2026-04-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echantillons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echantillon',
            name='reference_bouteille',
        ),
    ]
