# Generated by Django 6.0.4 on 2026-04-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echantillons', '0002_remove_echantillon_reference_bouteille'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='classification',
            field=models.CharField(blank=True, choices=[('extra_vierge', 'Extra vierge'), ('vierge', 'Vierge'), ('lampante', 'Lampante')], max_length=20),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='date_arrivee_stock',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='image_etiquette',
            field=models.ImageField(blank=True, null=True, upload_to='echantillons/'),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='quantite_estimee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='remarques',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='scellage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='statut_ceo',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='stock_arrive',
            field=models.BooleanField(default=False),
        ),
    ]
