# Generated by Django 6.0.4 on 2026-04-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echantillons', '0003_echantillon_classification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echantillon',
            old_name='reference',
            new_name='ref',
        ),
        migrations.RenameField(
            model_name='echantillon',
            old_name='date_modification',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='echantillon',
            name='camion_livraison',
        ),
        migrations.RemoveField(
            model_name='echantillon',
            name='date_arrivee_stock',
        ),
        migrations.RemoveField(
            model_name='echantillon',
            name='date_livraison_stock_souhaitee',
        ),
        migrations.RemoveField(
            model_name='echantillon',
            name='date_reception_echantillon',
        ),
        migrations.RemoveField(
            model_name='echantillon',
            name='image_etiquette',
        ),
        migrations.RemoveField(
            model_name='echantillon',
            name='nombre_bouteilles',
        ),
        migrations.RemoveField(
            model_name='echantillon',
            name='quantite',
        ),
        migrations.AddField(
            model_name='echantillon',
            name='camion_reserve',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='cite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='date_arrivee_echantillon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='date_livraison_stock',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='note_interne',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='quantite_cible_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='raison_refus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='echantillon',
            name='quantite_estimee',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='echantillon',
            name='scellage',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
