# Generated by Django 6.0.4 on 2026-04-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echantillons', '0004_rename_reference_echantillon_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='classification',
            field=models.CharField(blank=True, choices=[('extra_vierge', 'Extra vierge'), ('vierge', 'Vierge'), ('vierge_ordinaire', 'Vierge Ordinaire'), ('lampante', 'Lampante')], max_length=20),
        ),
        migrations.AlterField(
            model_name='echantillon',
            name='statut_ceo',
            field=models.CharField(choices=[('selectionne', 'Sélectionné'), ('en_negociation', 'En négociation'), ('achat_confirme', 'Achat confirmé'), ('refuse', 'Refusé')], default='selectionne', max_length=20),
        ),
    ]
