# Generated by Django 6.0.4 on 2026-05-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echantillons', '0005_alter_echantillon_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='edit_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
