# Generated by Django 4.2.30 on 2026-05-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echantillons', '0006_echantillon_edit_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echantillon',
            name='ref',
        ),
        migrations.AddField(
            model_name='echantillon',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='reference_bouteille',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
