# Generated by Django 6.0.4 on 2026-08-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echantillons', '0009_rename_scellage_num_citerne'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='budget_negociation_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='nb_renegociations',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
