# Generated by Django 6.0.4 on 2026-08-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echantillons', '0011_echantillon_remarque_collecteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echantillon',
            name='edit_history',
        ),
    ]
