# Generated by Django 6.0.4 on 2026-04-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('direction', 'Direction'), ('collecteur', 'Collecteur'), ('degustateur', 'Dégustateur'), ('laboratoire', 'Laboratoire'), ('chef_panel', 'Chef de Panel'), ('responsable_financier', 'Responsable Financier')], max_length=25),
        ),
    ]
