# Generated by Django 6.0.4 on 2026-09-25 18:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_chef_panel_to_chef_degustation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReinitialisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empreinte_code', models.CharField(max_length=128)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_le', models.DateTimeField()),
                ('nombre_essais', models.PositiveSmallIntegerField(default=0)),
                ('utilise', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_reinitialisation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['utilisateur', 'utilise', 'expire_le'], name='users_coder_utilisa_cf79af_idx')],
            },
        ),
    ]
