# Generated by Django 6.0.4 on 2026-09-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_codereinitialisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
